### PR TITLE
Add .github/workflows/shellcheck.yml

### PR DESCRIPTION
**Pull request by anthonyfok**
~2021-04-27: This PR is not quite ready for merging yet, will need to fix add_data.sh according to what ShellCheck tells us, and may need to add some overrides first.~

~2021-06-07: This PR is ready for review once #105 is reviewed and merged, as add_data.sh etc. have been made ShellCheck-clean in commit 313776fec815e194ee5c958e58aede796bce6bf2 therein.~

2021-06-14: Ready for review!  :-)

### CODE REVIEW

**Review by jvanulde — COMMENTED** [review]
Not sure what this does exactly... I ran the checks and it failed. Is that expected?

**Comment by anthonyfok** [comment]
> Not sure what this does exactly... I ran the checks and it failed. Is that expected?

Hey Joost!  Thanks for looking into this.
This is a PR to add a GitHub Action for ShellCheck, which is similar to the Lintly + Flake8 GitHub Actions/workflow `.github/workflows/lintly-flake8.yml` for Python scripts that you added back in August 2020, but for Bash.

This PR actually needs #105 as a prerequisite because I have lumped the ShellCheck fixes to add_data.sh in PR #105 in commit 313776f.  (My apologies, definitely not the best practice on my part, but it was "easier".  I shall try to avoid lumping unrelated fixes in one big PR in the future.)

**Comment by jvanulde** [comment]
> > Not sure what this does exactly... I ran the checks and it failed. Is that expected?
> 
> Hey Joost! Thanks for looking into this.
> This is a PR to add a GitHub Action for ShellCheck, which is similar to the Lintly + Flake8 GitHub Actions/workflow `.github/workflows/lintly-flake8.yml` for Python scripts that you added back in August 2020, but for Bash.
> 
> This PR actually needs #105 as a prerequisite because I have lumped the ShellCheck fixes to add_data.sh in PR #105 in commit [313776f](https://github.com/OpenDRR/opendrr-api/commit/313776fec815e194ee5c958e58aede796bce6bf2). (My apologies, definitely not the best practice on my part, but it was "easier". I shall try to avoid lumping unrelated fixes in one big PR in the future.)

Okay perfect.

**Comment by anthonyfok** [comment]
Hi @jvanulde,

Sorry to bother you again!  It turns out there are two ShellCheck warnings that I missed earlier that was fixed in commit 7ab2814 that I have pushed just now, hence I'm requesting your second review.

> Warning: ./python/gen_pygeoapi_config.sh:10:1: warning: Use 'cd ... || exit' or 'cd ... || return' in case cd fails. [SC2164]
> Warning: ./python/gen_pygeoapi_config.sh:21:7: warning: Remove surrounding $() to avoid executing output (or use eval if intentional). [SC2091]

Log from https://github.com/OpenDRR/opendrr-api/runs/2822572165?check_suite_focus=true

See https://github.com/koalaman/shellcheck/wiki/SC2164 and https://github.com/koalaman/shellcheck/wiki/SC2091 for ShellCheck documentation of the above warnings.

Many thanks!

**Review by drotheram — APPROVED** [review]
Looks good to me

**Comment by anthonyfok** [comment]
Thank you Drew and Joost!  Merging now.

**Pull request merged**
