### PR TITLE
filter out MMI shakemap files

### PR DESCRIPTION
**Pull request by drotheram**

### CODE REVIEW

**Review by wkhchow — APPROVED** [review]
looks good

**Review by anthonyfok — CHANGES_REQUESTED** [review]
Hey Drew,
Would be great if you could change `[^MMI]` to `(?<!MMI)` for a more precise match as noted above.
Many thanks!

**Comment by drotheram** [comment]
Thanks @anthonyfok changes implemented

**Review by anthonyfok — APPROVED** [review]
Looks great to me!  Thank you Drew!

**Pull request merged**
