### PR TITLE
update ES v7.16.1

### PR DESCRIPTION
**Pull request by drotheram**
Update ElasticSearch and Kibana version to latest 7.16.1

### CODE REVIEW

**Review by anthonyfok — APPROVED** [review]
Yay!  I love the Elasticsearch version upgrade!  Thank you @drotheram!

**Review by wkhchow — APPROVED** [review]

**Review by anthonyfok — CHANGES_REQUESTED** [review]
@drotheram Thank you for the heads-up that `elasticsearch:7.16.1` and `kibana:7.16.1` may not yet be available.  The latest available Docker images seem to have the tag 7.14.2.  I'll keep searching and see if 7.14.2 is OK or not re: log4j vulnerability.

**Comment by jvanulde** [comment]
We can wait, or we can build our own container with ES. Thoughts @drotheram  @anthonyfok

**Review by anthonyfok — APPROVED** [review]
LGTM!  And both the new elasticsearch and kibana 7.16.1 sprung up correctly and start showing log messages on my end.  While I haven't run the whole stack build to test it, I am pretty sure it will run fine.  :-)  Thanks again @drotheram and @jvanulde!

**Pull request merged**
